server:
  port: 40585

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/send_email
    username: postgres
    password: initdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
