sendemail:
  service:
    mailgun:
      serviceEndpoint: https://api.mailgun.net/v3/#domain_name/messages
      mailgunKey: 123
      mailgunDomain: 123
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
    database: HSQL
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:auth
    username: sa   