client:
  service:
    key: c
    url: api/v1/clients
sendemail:
  service:
    mailgun:
      serviceEndpoint: https://api.mailgun.net/v3/#domain_name/messages
      mailgunKey: 123
      mailgunDomain: 123
spring:
  jpa:
    hibernate:
      ddl-auto: update