sendemail:
  service:
    mailgun:
      serviceEndpoint: ${MAILGUN_URI}
      mailgunKey: ${MAILGUN_KEY}
      mailgunDomain: ${MAILGUN_DOMAIN}
spring:
  datasource:
    url: ${POSTGRE_URI}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
  jpa:
    hibernate:
      ddl-auto: update    
