sendemail:
  service:
    mailgun:
      serviceEndpoint: ${MAILGUN_URI}
      mailgunKey: ${MAILGUN_KEY}
      mailgunDomain: ${MAILGUN_DOMAIN}
spring:
  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    hibernate:
      ddl-auto: update