server:
  port: 40585
client:
  service:
    key: cecadbd7-e07c-48b2-b11d-038f7aaab4f6
    url: api/v1/clients
sendemail:
  service:
    mailgun:
      serviceEndpoint: https://api.mailgun.net/v3/#domain_name/messages
      mailgunKey: 123
      mailgunDomain: 123
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/send_email
    username: postgres
    password: initdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: updat
